name: Runner for terraform
run-name: Initialize terraform and apply infra

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  initialize-terraform-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the pull request code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform environment
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0  # Update the version as per your project needs

      # Step 3: Run 'terraform fmt' to check formatting
      - name: Run terraform fmt to check format
        run: terraform fmt -check -recursive

      # Step 4: Run 'terraform validate' to check validity
      - name: Run terraform validate to validate configuration
        run: terraform validate
