name: Terraform CI
 
# Trigger the workflow on pull requests and push to the test1 branch
on:
  pull_request:
    branches:
      - test  # Change this to the branch you want the CI to run on
 
jobs:
  terraform:
    name: Run terraform fmt and validate
    runs-on: ubuntu-latest
 
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2
 
    # Step 2: Setup Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Adjust the version if needed
 
    # Step 3: Run terraform fmt to check formatting
    - name: Run terraform fmt
      run: terraform fmt -check -recursive
 
    # Step 4: Run terraform validate to ensure configuration is correct
    - name: Run terraform validate
      run: terraform validate